### ISSUE TITLE
extra info about TODOs in README

### ISSUE THREAD

**Issue by roualdes** [csucdsi/website#26]
If you are interested in dividing and conquering your TODO list, found in the README file, then I'd be happy to help.  Some of them sound like quick notes to yourself though, with the real issue residing in your head. If you created an issue for each TODO and added some details about each, I'd be willing to give some of them a looksy.

**Comment by norcalbiostat** [comment]
Thanks for this push. upon reviewing it seems that most of them were addressed already - so i'm cleaning up that list and turning them into issues
